backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: /img
display_url: "https://peterpandev.netlify.app/"
site_url: "https://peterpandev.netlify.app/"
publish_mode: editorial_workflow

collections:
  - name: 'homepage'
    label: 'Homepage'
    folder: 'content/homepage'
    create: true
    slug: 'home'
    identifier_field: 'home'
    show_preview_links: true
    preview_path: '/'
    editor:
      preview: true
    fields:
      - label: 'Components'
        name: 'components'
        widget: 'list'
        types:
          - label: 'Heading'
            name: 'heading'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
          - label: 'Paragraph'
            name: 'paragraph'
            widget: 'object'
            fields:
              - { label: 'Text', name: 'text', widget: 'text' }
          - label: 'Accordion Group'
            name: 'accordionGroup'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Items'
                name: 'items'
                widget: 'list'
                fields:
                  - { label: 'Image', name: 'image', widget: 'image' }
                  - { label: 'Text', name: 'text', widget: 'text' }
                  - { label: 'Link', name: 'link', widget: 'string' }
          - label: 'Link Button'
            name: 'linkButton'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - label: 'Product'
            name: 'product'
            widget: 'object'
            fields:
              - { label: 'Product Name', name: 'productName', widget: 'string' }
              - { label: 'Product Description', name: 'productDescription', widget: 'string' }
              - { label: 'Product Image', name: 'productImage', widget: 'image' }
              - { label: 'Product Button Text', name: 'productButtonText', widget: 'string' }
              - { label: 'Product Button Link', name: 'productButtonLink', widget: 'string' }
              - { label: 'Product Old Price', name: 'productOldPrice', widget: 'string' }
              - { label: 'Product New Price', name: 'productNewPrice', widget: 'string' }
